name: Post Push
on:
  pull_request:
    branches:
      - 'main'
#test
jobs:
  Docker-Image-Scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Login to Docker Registry
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: thegenuinesloth
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker image
      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          push: false

      # Runs Docker image scan
      - name: Docker Image Scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1
        with:
          pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
          pcc_user: ${{ secrets.PCC_USER }}
          pcc_pass: ${{ secrets.PCC_PASS }}
          image_name: bitnami/nginx
