name: Post Push
on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
permissions: write-all

jobs:
  post-push:
    if: github.actor != 'github-actions[bot]'
    uses: Azure/tfmod-scaffold/.github/workflows/post-push.yaml@main
  build-and-scan:
    name: Build and scan image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Build the image
        run: docker build -t test-image .
      - name: Prisma Cloud image scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1
        with:
          pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
          pcc_user: ${{ secrets.PCC_USER }}
          pcc_pass: ${{ secrets.PCC_PASS }}
          image_name: test-image

# jobs:
#   dockerImages:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Generate matrix with all modules of this repository
#         id: set-matrix
#         run: |
#           echo "matrix=$(ls -l docker-images/ | grep '^d' | awk -F ' ' '{print $9}' | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT
#     outputs:
#       matrix: ${{ steps.set-matrix.outputs.matrix }}

#   docker-image-scan:
#     needs: dockerImages
#     runs-on: ubuntu-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         path: ${{ fromJson(needs.dockerImages.outputs.matrix) }}

#     steps:
#       - uses: actions/checkout@v3
